baseURL = '/'
languageCode = 'en-us'
title = 'North Side Coders Guild'
theme = 'ananke'

[[params.ananke_socials]]
name = "github"
url = "https://github.com/North-Side-Coders-Guild"

[markup.goldmark.renderer]
 unsafe = true


 [params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-blue"
  primary_color = "red"
  recent_posts_number = 3